#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : netbase
Version  : 5.4
Release  : 13
URL      : ftp://ftp.debian.org/debian/pool/main/n/netbase/netbase_5.4.tar.xz
Source0  : ftp://ftp.debian.org/debian/pool/main/n/netbase/netbase_5.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: netbase-data
Patch1: 0001-Add-a-Makefile-to-the-package.patch
Patch2: 0002-Use-rpcbind-for-sunrpc-services.patch

%description
No detailed description available

%package data
Summary: data components for the netbase package.
Group: Data

%description data
data components for the netbase package.


%prep
%setup -q -n netbase-5.4
%patch1 -p1
%patch2 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1488814995
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1488814995
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/defaults/etc/protocols
/usr/share/defaults/etc/services
